name: Build and Publish Helm Chart

on:
  push:
    branches:
      - 'main'
    paths:
      - 'example1/**'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Needed to push to gh-pages branch

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Create Helm package
        run: |
          mkdir -p .deploy
          helm package example1 --destination .deploy/

      - name: Setup GitHub Pages branch
        run: |
          git config --global user.email "github-actions@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          mv .deploy/*.tgz docs/

      - name: Update Helm repository index
        run: |
          cd docs
          helm repo index . --url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}
          cd ..

      - name: Commit and push changes
        run: |
          cd docs
          git add .
          git commit -m "Update Helm chart repository"
          git push origin main